name: Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  ossrs:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        run: |
          git clone https://github.com/ossrs/srs.git
          cd srs/trunk
          git checkout 70d5618979e5c8dc41b7cd87c78db7ca2b8a10e8 # 6.0.4
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
        with:
          # Build's context is the set of files located in the specified PATH or URL
          context: srs/
          # Path to the Dockerfile
          file: srs/trunk/Dockerfile
          push: true
          tags: ghcr.io/robinwongm/ossrs:6.0.4
  ffmpeg:
    runs-on: ubuntu-latest
    steps:
      - name: Build x264
        run: |
          git clone https://code.videolan.org/videolan/x264.git
          cd x264
          ./configure --prefix=$(pwd)/build --disable-asm --disable-cli --disable-shared --enable-static
          make -j2
          make install
      - name: Build x265
        run: |
          git clone https://bitbucket.org/multicoreware/x265_git.git
          cd x265_git/build/linux
          cmake -DCMAKE_INSTALL_PREFIX=$(pwd)/build -DENABLE_SHARED=OFF ../../source
          make -j2
          make install
          # https://github.com/markus-perl/ffmpeg-build-script/blob/master/build-ffmpeg#L559
          sed -i.backup 's/-lgcc_s/-lgcc_eh/g' build/lib/pkgconfig/x265.pc
      - name: Patch FFmpeg
        run: |
          git clone https://github.com/FFmpeg/FFmpeg.git
          cd FFmpeg
          git checkout n5.1.2
          cd ..
          git clone -b 5.1 https://github.com/runner365/ffmpeg_rtmp_h265.git
          cp ffmpeg_rtmp_h265/flv.h FFmpeg/libavformat/
          cp ffmpeg_rtmp_h265/flv*.c FFmpeg/libavformat/
      - name: Build FFmpeg
        run: |
          export PKG_CONFIG_PATH=$(pwd)/x264/build/lib/pkgconfig:$(pwd)/x265_git/build/linux/build/lib/pkgconfig
          cd FFmpeg
          ./configure \
            --prefix=$(pwd)/build \
            --enable-gpl --enable-nonfree --enable-pthreads --extra-libs=-lpthread \
            --disable-asm --disable-x86asm --disable-inline-asm --disable-shared --disable-debug --disable-doc \
            --enable-decoder=aac --enable-decoder=aac_fixed --enable-decoder=aac_latm --enable-encoder=aac \
            --enable-libx264 --enable-libx265 \
            --pkg-config-flags='--static' \
            --extra-ldexeflags="-static"
          make -j2
          make install
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ffmpeg
          path: |
            FFmpeg/build/bin/ffmpeg
